import {
  ArrowLeft,
  ChevronRight,
  CircleCheck,
  Copy,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileCode,
  FileImage,
  FileJson,
  FileCog,
  FileText,
  FileType,
  Folder,
  FolderPlus,
  History,
  House,
  LayoutGrid,
  Link as LinkIcon,
  List as ListIcon,
  Lock,
  LogOut,
  Mail,
  Moon,
  Package,
  PackagePlus,
  Pencil,
  Save,
  Sun,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

// Mirrors api/internal/adminui/icons.go: the same lucide-react icon set,
// referenced by the same names, so a page just names an icon instead of
// importing it directly.
const icons: Record<string, LucideIcon> = {
  package: Package,
  folder: Folder,
  "folder-plus": FolderPlus,
  "package-plus": PackagePlus,
  file: File,
  "file-code": FileCode,
  "file-json": FileJson,
  "file-text": FileText,
  "file-image": FileImage,
  "file-cog": FileCog,
  "file-archive": FileArchive,
  "file-type": FileType,
  "trash-2": Trash2,
  upload: Upload,
  download: Download,
  pencil: Pencil,
  "external-link": ExternalLink,
  history: History,
  lock: Lock,
  "layout-grid": LayoutGrid,
  list: ListIcon,
  "chevron-right": ChevronRight,
  sun: Sun,
  moon: Moon,
  house: House,
  "arrow-left": ArrowLeft,
  save: Save,
  x: X,
  "triangle-alert": TriangleAlert,
  "circle-check": CircleCheck,
  user: User,
  users: Users,
  "log-out": LogOut,
  mail: Mail,
  link: LinkIcon,
  copy: Copy,
  eye: Eye,
  "eye-off": EyeOff,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Component = icons[name];
  if (!Component) return null;
  return <Component className={className} aria-hidden="true" />;
}
